'''
Build content/static/trivia/bank.js from the cached Trivia API response.

The cache is the raw API shape.  The game wants six categories, a couple
of which are several API categories merged, and it wants the fields under
the names app.js reads.  Doing both here means the browser loads a bank it
can use directly, with no adapter pass at startup and no unused fields.

    python3 scripts/build_trivia_bank.py
'''

import json
import os
import sys

# Resolved against the repo, not the working directory, so the script runs
# the same from anywhere.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(
    ROOT, 'trivia-sources', 'the-trivia-api-family-text-choice.json')
TARGET = os.path.join(ROOT, 'content', 'static', 'trivia', 'bank.js')

# (id, label, [API categories that feed it]).  Order is the order the
# tiles appear in, and the index picks the artwork and colour that
# artwork.css measured off it, so reordering reskins the board.
CATEGORIES = [
    ('geography', 'Geography', ['geography']),
    ('entertainment', 'Entertainment', ['film_and_tv', 'music']),
    # Society and Culture is mythology, religion and customs, which reads
    # as history-adjacent, and history on its own has the thinnest pool of
    # easy questions in the set (40).
    ('history', 'History', ['history', 'society_and_culture']),
    ('arts_and_literature', 'Arts and Literature', ['arts_and_literature']),
    ('science', 'Science', ['science']),
    # Food and Drink keeps Sports and Leisure from being far and away the
    # smallest category (452 questions, 47 of them easy).
    ('sport_and_leisure', 'Sports and Leisure',
     ['sport_and_leisure', 'food_and_drink']),
]

# Deliberately not served.  Listed rather than ignored so that a category
# appearing in the cache that nobody has decided about is an error instead
# of a silent omission.
DROPPED = ['general_knowledge']

DIFFICULTIES = ['easy', 'medium', 'hard']


def load(source=SOURCE):
    with open(source) as handle:
        cache = json.load(handle)
    questions = cache['questions']
    if len(questions) != cache['questionCount']:
        raise ValueError('The cache question count does not match its records.')
    return questions


def build(questions):
    '''Map the cache onto the served bank.  Returns (bank, categories).'''
    routes = {}
    for index, (cat_id, _, sources) in enumerate(CATEGORIES):
        for source in sources:
            if source in routes:
                raise ValueError('{} feeds two categories'.format(source))
            routes[source] = cat_id

    known = set(routes) | set(DROPPED)
    seen = {q['category'] for q in questions}
    unknown = seen - known
    if unknown:
        raise ValueError(
            'cache has categories nobody has decided about: {}'.format(
                ', '.join(sorted(unknown))))

    bank, ids = [], set()
    for question in questions:
        target = routes.get(question['category'])
        if target is None:
            continue
        if question['id'] in ids:
            continue
        ids.add(question['id'])
        difficulty = question['difficulty']
        if difficulty not in DIFFICULTIES:
            raise ValueError('{}: unknown difficulty {!r}'.format(
                question['id'], difficulty))
        # The names on the right are what app.js reads.
        bank.append({
            'id': question['id'],
            'prompt': question['question']['text'],
            'answer': question['correctAnswer'],
            'incorrectAnswers': question['incorrectAnswers'],
            'sourceCategory': target,
            'sourceDifficulty': difficulty,
        })

    categories = [[cat_id, label] for cat_id, label, _ in CATEGORIES]
    return bank, categories


def render(bank, categories):
    return (
        '// Generated by scripts/build_trivia_bank.py -- do not edit.\n'
        'window.TRIVIA_CATEGORIES = {};\n'
        'window.TRIVIA_QUESTIONS = {};\n'.format(
            json.dumps(categories, ensure_ascii=False),
            json.dumps(bank, ensure_ascii=False)))


def main():
    questions = load()
    bank, categories = build(questions)

    counts = {}
    for question in bank:
        key = (question['sourceCategory'], question['sourceDifficulty'])
        counts[key] = counts.get(key, 0) + 1

    print('{:<22}{:>7}{:>8}{:>7}{:>8}'.format(
        'category', 'easy', 'medium', 'hard', 'total'))
    for cat_id, label, sources in CATEGORIES:
        row = [counts.get((cat_id, d), 0) for d in DIFFICULTIES]
        print('{:<22}{:>7}{:>8}{:>7}{:>8}   {}'.format(
            label, row[0], row[1], row[2], sum(row), ' + '.join(sources)))
    print('{:<22}{:>30}'.format('TOTAL', len(bank)))
    print('dropped: {} ({} questions)'.format(
        ', '.join(DROPPED),
        sum(1 for q in questions if q['category'] in DROPPED)))

    with open(TARGET, 'w') as handle:
        handle.write(render(bank, categories))
    print('wrote {} ({:,} bytes)'.format(TARGET, os.path.getsize(TARGET)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
